title: Qian Wu Blog
description: Welcome to my coding blog! As a professional programmer, I share my expertise in coding, creating, installing OS, CLI, frontend, backend, and more. Join me on my journey to explore the fascinating world of programming, and let's learn together.

url: https://qianwublog.me/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
 style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
 # github: qianwublog
 # twitter: qianwublog
 # facebook: qianwublog
 # email: brimaidesigns@gmail.com
 # linkedin: qianwublog

google_analytics: "G-7X7TWLX6FS"

disqus:
 shortname: qianwublog

url: "https://qianwublog.me"
plugins:
  - jekyll-sitemap
  - jekyll-paginate
